### ISSUE TITLE
--version

### ISSUE THREAD

**Issue by lskatz** [nawrockie/dnaorg_annotate_genomes.pl#25]
Could you add a flag to print the version and exit 0?  Thank you!

**Comment by nawrockie** [comment]
@lskatz , is this good enough? :
```
$ v-annotate.pl -h | head -n 2 | tail -n 1
# VADR 1.1.1 (July 2020)
```
or
```
$ v-annotate.pl -h | head -n 2 | tail -n 1 | awk '{ print $3 }'
1.1.1
```

With  -h, the program exits with 0 status

**Comment by lskatz** [comment]
It's good if it's a guaranteed way to parse the version long-term!  

However, it's a sort of awkward way to parse the version and check it in an automated pipeline.  It might be awkward to document this as the official way to print the version.  Another issue is that it might be difficult for you to guarantee this as the permanent way to check the version.

**Comment by nawrockie** [comment]
Yes, that is guaranteed to work long term. The 'official way' to print the version is the -h option which prints both version and help information. I'd rather just leave this the way it is. 

In general, you usually need to parse the output of --version for any program because the format of the output of that option varies. As an example take the output of gcc --version on my Mac: 

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
