### ISSUE TITLE
Test failed when running `do-all-tests.sh` with VADR 1.3

### ISSUE THREAD

**Issue by taltman** [nawrockie/dnaorg_annotate_genomes.pl#44]
Using VADR 1.3, I ran the `do-all-tests.sh` script. All tests except one passed. Below find the output for the failed test. I can also share the Docker container in which VADR ran, so that you can exactly reproduce the environment.

Thanks!

[vadr-error.txt](https://github.com/ncbi/vadr/files/7694636/vadr-error.txt)

**Comment by nawrockie** [comment]
@taltman : my guess is that you've run out of memory. It's failing at the cmalign step which is memory intensive, and the recommended amount of available RAM is 8Gb. How much memory are you allocating in the Docker container? 

If you only want to use VADR for SARS-CoV-2 analysis, it only requires 2Gb RAM (per thread) because it uses a different alignment algorithm than cmalign in which case you can ignore that test failure.

**Comment by taltman** [comment]
That probably is it, as I was using just shy of 8 GB of RAM. Time-permitting, I'll re-run it with more memory allocated.

**Comment by taltman** [comment]
Confirmed that re-running it with more memory allocated seems to have resolved the discrepancy.
