### ISSUE TITLE
Double-entries in `.tbl` file

### ISSUE THREAD

**Issue by taltman** [nawrockie/dnaorg_annotate_genomes.pl#50]
I've noticed that there are often double-entries in the generated tbl file:

```
<1	1358	misc_feature
			note	similar to nsp3
<1	1358	misc_feature
			note	similar to nsp3
1359	2678	misc_feature
			note	similar to nsp4
1359	2678	misc_feature
			note	similar to nsp4
2679	3391	misc_feature
			note	similar to 3C-like proteinase
2679	3391	misc_feature
			note	similar to 3C-like proteinase
```

See the attached file (had to append the `.txt` suffix to attach to the GitHub issue):
[SRR8389791.vadr.fail.tbl.txt](https://github.com/ncbi/vadr/files/7721954/SRR8389791.vadr.fail.tbl.txt)

**Comment by nawrockie** [comment]
This is because the `.minfo` file has two versions of each mat_peptide, one for the orf1a CDS and one for the orf1ab CDS. If you look at the SARS-CoV-2 RefSeq (https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2/) you'll see there are two nsp3 mat_peptides entries there as well. This is NCBI convention: each CDS becomes a protein record and each protein record has all associated mat_peptides with it. So in the internal NCBI pipelines it was desired that the vadr .tbl output files create two copies of the shared mat_peptides. 

You can use the `--nomisc` option to have the misc_features reported as mat_peptides in the output feature table, and in that case they will have protein_id fields that differentiate them as to which protein they pertain to.

Let me know if that's not clear or you have additional questions/confusion.

**Comment by taltman** [comment]
Hi @nawrockie,

The `--nomisc` option is *exactly* what I needed. This will greatly improve the annotations for our distant CoV genomes. Thank you!
