### ISSUE TITLE
VADR doesn't detect annotated segments

### ISSUE THREAD

**Issue by halabikeren** [nawrockie/dnaorg_annotate_genomes.pl#56]
Hi dear team,

I executed VADR on 119 genome accession of species from the Flaviviridae family. Out of the 82 for which VADR found reliable annotation, in 5 accessions the poylprotein cds annotation, which I expected to find in all accessions, wasn't apparent (AY632536, KY523073, MN649260, MT276210, NC_038912). When examining one of these accessions manually (AY632536), I saw that the polyprotein cds was in fact annotated in it.

Please find below the input on which vadr  was executed and the produced output. 
[vadr.zip](https://github.com/ncbi/vadr/files/7844731/vadr.zip)

The command I used was:
`v-annotate.pl --mkey flavi --mdir $VADRMODELDIR/vadr-models-flavi-1.2-1 unaligned.fasta flaviviridae_genomes_annotation`

Additional info:
I am using version 1.4, installed with conda
I am using the vadr
 [flavi models version 1.2-1](https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/flaviviridae/CURRENT/) (as seen in the command above)

I wonder if in such case I should complement vadr annotation with manually annotated data. What would you suggest?

Many thanks!

**Comment by nawrockie** [comment]
I took a look at your 5 sequences and ran them through vadr 1.4 with
the model set vadr-models-flavi-1.2-1. I can confirm that none of the
5 sequences you listed have a CDS with exactly the product value
'polyprotein', but 2 do have a CDS with a product value of 'flavivirus
polyprotein' and 1 has a CDS with a product value of 'polyprotein
precursor'. The other two don't have any CDS that matches polyprotein,
(more on these two below). 

For the 3 that do have a CDS with 'polyprotein' as part of the product
value, but not exactly 'polyprotein', I'm guessing your question is
why is it not exactly 'polyprotein'. 

The reason is that VADR annotates each sequence based on the
annotation for its 'best-matching' model in the model set. (The
identity of the best-matching model for each sequence is contained in
several of the vadr output files, including the .sqc and .ftr output
files:
https://github.com/ncbi/vadr/blob/master/documentation/formats.md)

For example, for AY632536, the best-matching model is NC_009026. The
annotation for NC_009026 is in the 'model info' file 'flavi.minfo'. This
annotation derives from the GenBank record for NC_009026
(https://www.ncbi.nlm.nih.gov/nuccore/NC_009026.2/). The relevant
lines from the flavi.minfo file include 'NC_009026':

```
MODEL NC_009026 blastdb:"NC_009026.vadr.protein.fa" length:"10815"
FEATURE NC_009026 type:"gene" coords:"105..10394:+" parent_idx_str:"GBNULL" gene:"flavivirus polyprotein gene"
FEATURE NC_009026 type:"CDS" coords:"105..10394:+" parent_idx_str:"GBNULL" gene:"flavivirus polyprotein gene" product:"flavivirus polyprotein"
```

You can see that there is 1 CDS, and it has the product value
'flavivirus polyprotein', as opposed to just 'polyprotein'.

If you want the output to have just 'polyprotein' for all sequences
for which the best matching model is NC_009026, you can modify the
.minfo file to have 

```
FEATURE NC_009026 type:"CDS" coords:"105..10394:+" parent_idx_str:"GBNULL" gene:"flavivirus polyprotein gene" product:"polyprotein"
```

Also, there are 9 models out of the 156 in the vadr-models-flavi-1.2-1
model set that do not have a CDS annotated that includes the substring
'polyprotein' in it's product value. Two of these are models that are
best-matching to one of your five sequences, specifically:

```
sequence     best-matching-model
KY523073     NC_034225
NC_038912    NC_038912
```

For NC_034225, the model is only 2629nt long and it is a putative
glycoprotein gene, and so does not include a full length polyprotein
CDS.

NC_038912 is classical swine fever virus which has a single CDS of
length roughly 12Kb which has the product value: 'Hog cholera
virus'. Because this is a flavivirus, I'm assuming this is the
polyprotein, it just isn't named as such in the GenBank record.

Does this answer your question?

**Comment by halabikeren** [comment]
Many thanks for the elaborated answer!

Indeed, your response answers my question. As far as I understand, inconsistent annotations in the model accessions lead to inconsistent annotations across the input accessions for annotation. I can deal with this in two ways:
1. "unite" the annotations in the flavi model (i.e., flavi.minfo) into a single "corpus".
2. "unite" the matched annotations in the output of the annotation procedure.
In your opinion, what is the better approach here?

As for problematic input accessions, such as NC_034225, which consists only of a partial CDS, I could either exclude it from my analysis or rebuild the flavi model , while including such partial accessions, to accommodate for it.
Am I correct in my conclusion?

Many thanks again!

**Comment by nawrockie** [comment]
>In your opinion, what is the better approach here?

It depends on exactly what you are doing, but I think modifying flavi.minfo is probably better as you'll only have to do it once and it will then cause v-annotate.pl to create consistent annotations repeatedly.

>As for problematic input accessions, such as NC_034225, which consists only of a partial CDS, I could either
>exclude it from my analysis or rebuild the flavi model , while including such partial accessions, to accommodate for it.
> Am I correct in my conclusion?

Yes, I think so. NC_034225 doesn't include a full polyprotein. I was unable to find a full genome for that virus (Mogiana tick virus) but I admit I could have tried harder, so I don't think that means that there definitely is not a full genome. Alternatively you could keep the partial accession models in, and just treat sequences that match best to them differently in your analysis. That is, for those seqs that match best to one of those models, you just won't have polyprotein annotation.

**Comment by halabikeren** [comment]
Thank you for the informative response!
