### ISSUE TITLE
Problem about fetching and parsing protein feature table file(s)

### ISSUE THREAD

**Issue by hgwu80** [nawrockie/dnaorg_annotate_genomes.pl#62]
Hi Dr. Nawrocki,
I used the vadr in cluster. The problem is that the hqueue computing node of the cluster cannot connect to the network. I used the options --infa  --inft to specify the local fasta sequence and feature table. But, I met a problem "ERROR in vdr_EutilsFetchToFile, problem fetching NP_536428.1 (undefined)". I knew it is connect issue. So, how to deal with it?
Thanks in advance.
Best,
Huiguang

**Comment by nawrockie** [comment]
@hgwu80 : unfortunately there is currently no way around this issue if the `--inft` feature table you are building a model from includes CDS regions, because you need to be connected to the internet for vadr to obtain the protein information needed for the CDS.

However, it is only the `v-build.pl` step that requires access to the internet, so if you are able to run just this one step not on the cluster, but rather on a machine connected to the internet, you could then use `v-annotate.pl` for annotation on the cluster later, because annotation doesn't require an internet connection.

Also, for monkeypox you'll want to use the `--forcelong` and `--skipbuild` options with `v-build.pl`, if you aren't already.

**Comment by hgwu80** [comment]
OK! Your suggestion is useful for me. Thank you very much!

**Comment by nawrockie** [comment]
@hgwu80 : you're welcome. Let me know if you have further problems/questions.

**Comment by hgwu80** [comment]
Hi Dr. Nawrocki,

I followed your instruction. In the build step, I used the --forcelong and --skipbuild options. In the annotation step, I used the command as below: 
v-annotate.pl --mdir NC_003310 --mkey NC_003310.vadr mpxv.fasta  mpxv_annotation

But, I got a fatal error: 
ERROR in utl_FileValidateExistsAndNonEmpty(), file NC_003310/NC_003310.vadr.cm (CM file, due to  --mdir --mkey) does not exist.

What am I doing wrong?

Thanks in advance.
Best,
Huiguang

**Comment by nawrockie** [comment]
Hi @hgwu80 , I am currently in the process of testing vadr on monkeypox and have found several issues that I'm still trying to figure out solutions to. I am hopeful that I will be able to get back to you in the next few days with some instructions.

**Comment by hgwu80** [comment]
Thank you very much for your kindly help and hard work!

**Comment by nawrockie** [comment]
@hgwu80 : just an update - this is taking longer than I had hoped and I won't have any instructions for you until late next week at the earliest.

**Comment by nawrockie** [comment]
@hgwu80 : I've made a VADR monkeypox virus model available. You can find instructions for downloading the model files and using it to annotate sequences here:

https://github.com/ncbi/vadr/wiki/Monkeypox-virus-annotation

Please let me know if you have any questions, or have any issues.

**Comment by hgwu80** [comment]
Thanks a lot for taking the time to help me sovle this issue.
