### ISSUE TITLE
Unable to build a model 

### ISSUE THREAD

**Issue by anilsurathu** [nawrockie/dnaorg_annotate_genomes.pl#64]
I am building models for each of the 12 segments of Colorado Tick Fever Virus and annotating them. I am able to build models and annotate all segments except for segment 9. Here is the command I am using and the error I get. Let me know if you need additional information. 

I am unable to find any information on this error. Can you please help? Thank you. 

v-build.pl -f --group CTFV --subgroup S9 NC_004180 /output/path/models/refseq/CTFV_s9

v-build.pl :: build homology model of a single sequence for feature annotation
VADR 1.4.2 (Jul 2022)
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
date:              Fri Oct 14 10:31:35 2022
$VADRBLASTDIR:     /xxxx/opt/miniconda3/envs/vadr/bin
$VADREASELDIR:     /xxxx/opt/miniconda3/envs/vadr/bin
$VADRINFERNALDIR:  /xxxx/opt/miniconda3/envs/vadr/bin
$VADRSCRIPTSDIR:   /xxxx/opt/miniconda3/envs/vadr/share/vadr-1.4.2/vadr

 accession/model name:           NC_004180
 output directory:                /output/path/models/refseq/CTFV_s9
 forcing directory overwrite:    yes [-f]
 specify model group is < s>:     CTFV [--group]
 specify model subgroup is < s>:  S9 [--subgroup]
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 Fetching FASTA file                                          ... done. [    4.4 seconds]
 Parsing FASTA file                                           ... done. [    0.0 seconds]
 Fetching feature table file                                  ... done. [    3.4 seconds]
 Parsing feature table file                                   ... done. [    0.0 seconds]
 Fetching and parsing protein feature table file(s)           ... done. [    6.9 seconds]
 Pruning data read from GenBank                               ... done. [    0.0 seconds]
 Reformatting FASTA file to Stockholm file                    ... done. [    0.1 seconds]
 Building BLAST nucleotide database                           ... done. [    3.8 seconds]
 Finalizing feature information                               ... done. [    0.0 seconds]
 Translating CDS                                              ...
ERROR in sqf_EslTranslateCdsToFastaFile, problem translating CDS feature, unable to find expected translated sequence in /output/path/models/refseq/CTFV_s9/CTFV_s9.vadr.cds.esl-translate.2.fa:
        seq: NC_004180.1/41..1849:+
        expected sequence:source=NC_004180.1/41..1849:+,coords=1..1806

**Comment by nawrockie** [comment]
Hi @anilsurathu,

The reason for the v-build.pl failure has to do with the fact that
the RefSeq annotation for NC_004180 has two CDS and associated
translated proteins, one of which uses a stop codon at positions
1052..1054 and one which ignores this stop codon and ends at position
1849. The second CDS includes special annotation that explains this:
`transl_except=(pos:1052..1054,aa:OTHER)` and 
`note="one of three different amino acids (arginine,
cysteine or tryptophan) is incorporated at amino
acid position 338 during read through`.

This situation violates internal assumptions that VADR makes, namely
that a stop codon causes a CDS to end, and this violation is what is
causing v-build to fail.

To get around this, I was able to build two models, one with each CDS
and combine them to make a single model that will 'work' with an
important caveat (explained below).

To build these two models and combine them, I ran the following
commands, with # lines indicating comments briefly explaining what
each command is doing:

```
# build models
v-build.pl --infa mod.NC_004180.fa --inft mod1.NC_004180.ft -f --group CTFV --subgroup S9 NC_004180 CTFV_s9
v-build.pl --inft mod2.NC_004180.ft -f --group CTFV --subgroup S9 NC_004180 CTFV_s9.2

# add 41..1054 translated CDS to blast DB
cat CTFV_s9.2/CTFV_s9.2.vadr.protein.fa >> CTFV_s9/CTFV_s9.vadr.protein.fa
$VADRBLASTDIR/makeblastdb -dbtype prot -in CTFV_s9/CTFV_s9.vadr.protein.fa

# add 41..1054 translated CDS to HMMER DB
cat CTFV_s9.2/CTFV_s9.2.vadr.protein.hmm >> CTFV_s9/CTFV_s9.vadr.protein.hmm
rm CTFV_s9/CTFV_s9.vadr.protein.hmm.h*
$VADRHMMERDIR/hmmpress CTFV_s9/CTFV_s9.vadr.protein.hmm

# add 41..1054 CDS to .minfo file
grep FEATURE CTFV_s9.2/*minfo >> CTFV_s9/CTFV_s9.vadr.minfo
```

I've attached this as `build.sh.txt`, and also the files
`mod.NC_004180.fa.txt`, `mod1.NC_004180.ft` and `mod2.NC_004180.ft`
that are needed to make the script work.  (These files end in `.txt`
because github only allows you to attach files with certain suffixes,
including `.txt`, so you'll have to rename them to remove the `.txt`
suffix before you run `build.sh` locally. 

You can then run v-annotate.pl with this model on a sequence file
my.fa with:

```
v-annotate.pl -f --nomisc --mdir CTFV_s9 --mkey CTFV_s9.vadr my.fa va-my
```

The caveat is that using v-annotate.pl with this model will result in
nearly all sequences failing, because sequences that include the stop
codon at reference positions 1052..1054 will have an early stop in the
longer CDS, which causes a fatal alert for vadr. All that said, both
CDS will still be annotated in the output annotation files.

Let me know if you have problems/questions.
[build.sh.txt](https://github.com/ncbi/vadr/files/9802575/build.sh.txt)
[mod2.NC_004180.ft.txt](https://github.com/ncbi/vadr/files/9802577/mod2.NC_004180.ft.txt)
[mod1.NC_004180.ft.txt](https://github.com/ncbi/vadr/files/9802578/mod1.NC_004180.ft.txt)
[mod.NC_004180.fa.txt](https://github.com/ncbi/vadr/files/9802579/mod.NC_004180.fa.txt)

**Comment by anilsurathu** [comment]
@nawrockie 

I was able to get it to work using your solution. Thank you for a quick and comprehensive response.
