### ISSUE TITLE
ERROR in sqf_EslTranslateCdsToFastaFile, problem translating CDS feature, unable to find expected translated sequence in EU156171/EU156171.vadr.cds.esl-translate.2.fa:

### ISSUE THREAD

**Issue by NailouZhang** [nawrockie/dnaorg_annotate_genomes.pl#66]
Hi,
I try to build the library for [Paramyxoviridae](https://viralzone.expasy.org/556)  with fellow code,
v-build.pl --forcelong \
 -f \
 --infa EU156171.1.fasta\
 --gb --ingb EU156171.1.gb \
 --ttbl 11\
 EU156171 EU156171

The output presented,
#v-build.pl :: build homology model of a single sequence for feature annotation
#VADR 1.5 (Sep 2022)
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
#date:              Mon Nov 14 19:00:50 2022
#$VADRBLASTDIR:    VADR/ncbi-blast/bin
#$VADREASELDIR:     VADR/infernal/binaries
#$VADRINFERNALDIR:  VADR/infernal/binaries
#$VADRSCRIPTSDIR:  VADR/vadr
#
#accession/model name:                                      EU156171
#output directory:                                          EU156171
#forcing directory overwrite:                               yes [-f]
#read single sequence fasta file from , don't fetch it:  EU156171.1.fasta [--infa]
#parse a genbank file, not a feature table file:            yes [--gb]
#read genbank file from , don't fetch it:                EU156171.1.gb [--ingb]
#allow long models > 25Kb in length:                        yes [--forcelong]
#use NCBI translation table  to translate CDS:           11 [--ttbl]
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#Parsing FASTA file                                           ... done. [    0.0 seconds]
#Parsing GenBank file                                         ... done. [    0.0 seconds]
#Pruning data read from GenBank                               ... done. [    0.0 seconds]
#Reformatting FASTA file to Stockholm file                    ... done. [    0.0 seconds]
#Building BLAST nucleotide database                           ... done. [    1.8 seconds]
#Finalizing feature information                               ... done. [    0.0 seconds]
#Translating CDS                                              ... 
**ERROR in sqf_EslTranslateCdsToFastaFile, problem translating CDS feature, unable to find expected translated sequence in EU156171/EU156171.vadr.cds.esl-translate.2.fa:
	seq: EU156171.1/2535..3518:+
	expected sequence:source=EU156171.1/2535..3518:+,coords=1..981/**
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#

# This may be caused by the gene structure of Paramyxoviridae. How can I resolve this？

# Could you help me to test and build a database for Paramyxoviridae?

**Comment by nawrockie** [comment]
Hi @NailouZhang  ,

I looked into getting v-build.pl to work for EU156171. One way to make
it work is the following:

- The input .gb file you use should have only two differences from the
  file that is downloaded from:

  https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=EU156171&rettype=gb&retmode=text

Those two differences can be shown by diff:

```
$ diff mod.EU156171.1.gb EU156171.1.gb
93c93
<      CDS             join(2535..3513,3513..3670)
---
>      CDS             2535..3667
106c106
<      CDS             join(2535..3514,3513..3519)
---
>      CDS             2535..3518
```

I've included the mod.EU156171.1.gb.txt file here.

The reason these changes are necessary is because the V and W proteins
both use RNA editing to add a either 1 G nucleotide (V protein) or 2 G
nucleotides (W protein) to the genomic sequence prior to translation,
as you probably already know. This is indicated in the following
misc_feature annotation in the GenBank record:

```
     misc_feature    3513..3514
                     /gene="P/V/C"
                     /note="RNA editing inserts one G residue to
                     generate mRNA
                     encoding the V protein and two G residues to
                     generate mRNA
                     encoding the W protein"
```

Because positions 3513 and 3514 are both G, this can be 'solved' in
v-build.pl by pretending like there is a frameshift and positions
2535..3513 and 3513..3670 are joined to make the V protein CDS, and
positions 2535..3514 and 3513..3518 are joined to make the W
protein CDS, thus adding 1 or 2 Gs to the CDS from the genomic
sequence. 

I also noticed that you were using `--tt 11` in your
command but I think EU156171 uses the standard genetic code (doesn't
it?) so you should not use this option.

Please give this a try and let me know if it works or not. Note, the
EU156171.fasta file you use should include the unmodified fasta
sequence downloaded from: 

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=EU156171&rettype=fasta&retmode=text

**Comment by nawrockie** [comment]
[mod.EU156171.1.gb.txt](https://github.com/ncbi/vadr/files/10005567/mod.EU156171.1.gb.txt)

**Comment by NailouZhang** [comment]
Hi Eric,
Thanks a lot.
This work!
W(x..y)
V(x..z)
Insert G,G(m,m+1)

Treated as frameshift
W join (x..m+1,m..y-2)
V join (x..m,m..y-1)
